services:
  
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/workspace
    links:
      - 'db'
      - 'emqx'

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  emqx:
    user: root
    image: "emqx:4.4.3"
    restart: always
    ports:
      - "18083:18083" 
      - "1883:1883"
    volumes:
      - ./data/emqx/data:/opt/emqx/data
      - ./data/emqx/log:/opt/emqx/log
    environment:
      - EMQX_DASHBOARD__DEFAULT_USER__LOGIN=sergio
      - EMQX_DASHBOARD__DEFAULT_USER__PASSWORD=prueba

volumes:
  postgres-data:
