# Generated by Django 5.0.4 on 2025-03-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='identificador',
            field=models.CharField(default='99999', max_length=100, unique=True),
        ),
    ]
